// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Survey.Data;

#nullable disable

namespace Survey.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250528192951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Survey.Models.UserSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EatOutRating")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LikesBeefStirFry")
                        .HasColumnType("bit");

                    b.Property<bool>("LikesChickenStirFry")
                        .HasColumnType("bit");

                    b.Property<bool>("LikesOther")
                        .HasColumnType("bit");

                    b.Property<bool>("LikesPapAndWors")
                        .HasColumnType("bit");

                    b.Property<bool>("LikesPasta")
                        .HasColumnType("bit");

                    b.Property<bool>("LikesPizza")
                        .HasColumnType("bit");

                    b.Property<int>("ListenToRadioRating")
                        .HasColumnType("int");

                    b.Property<int>("WatchMoviesRating")
                        .HasColumnType("int");

                    b.Property<int>("WatchTVRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Surveys");
                });
#pragma warning restore 612, 618
        }
    }
}
